
[package]
authors = ["YUCLing <luotianyi@luotianyi.me>"]
edition = "2021"
name = "ui"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi.workspace = true
napi-derive.workspace = true
font-kit = { git = "https://github.com/YUCLing/font-kit.git", rev = "bf5afc70b5afbcfa3de1b7e43b0ecae7524318cd", features = [
  "source-fontconfig-dlopen",
] }

[build-dependencies]
napi-build = "2"
