packages:
  - "."
  - "gui/"
  - "modules/*"
catalog:
  "@electron/fuses": ^2.1.3
  keyv: 6.0.0-beta.4
allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  unrs-resolver: true
patchedDependencies:
  # inlineDynamicImports is deprecated in Vite 8
  "@electron-forge/plugin-vite": patches/@electron-forge__plugin-vite.patch
  # Drop other adapter support, as we always use node:sqlite
  "@keyv/sqlite": patches/@keyv__sqlite.patch
  # Fixes compatibility with latest rpmbuild
  electron-installer-redhat@3.4.0: patches/electron-installer-redhat@3.4.0.patch
blockExoticSubdeps: false
nodeLinker: hoisted
overrides:
  # See https://github.com/electron/electron/issues/51619
  "yauzl@2.10.0": "^3.3.1"
  # Got (cacheable-request) uses Keyv 5, but we are using v6, they are mostly compatible, we are overriding it here, and patch cacheable-request
  "got>keyv": "catalog:"
  "cacheable-request>keyv": "catalog:"
  # Our environment is locked to Node.JS 24+, so there will always be node:sqlite
  "@keyv/sqlite>better-sqlite3": "-"
  "@keyv/sqlite>sqlite3": "-"
  # Safe to upgrade (no actual breaking changes for this project)
  "@electron-forge/plugin-fuses>@electron/fuses": "catalog:"
