packages:
  - "."
  - "gui/"
  - "modules/*"
allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  unrs-resolver: true
patchedDependencies:
  # Patches better-sqlite3 out of package.json, so Electron package won't be confused
  "@keyv/sqlite": patches/@keyv__sqlite.patch
  # Fixes event listener leak
  cacheable-request@13.0.19: patches/cacheable-request@13.0.19.patch
  # Fixes compatibility with latest rpmbuild
  electron-installer-redhat@3.4.0: patches/electron-installer-redhat@3.4.0.patch
  # Fixes event listener leak (comes with cacheable-request fix before)
  keyv@6.0.0-alpha.3: patches/keyv@6.0.0-alpha.3.patch
blockExoticSubdeps: false
nodeLinker: hoisted
# See https://github.com/electron/electron/issues/51619
overrides:
  "yauzl@2.10.0": "^3.3.1"
  # Got (cacheable-request) uses Keyv 5, but we are using v6, they are mostly compatible, we are overriding it here, and patch cacheable-request
  "got>keyv": "$keyv"
  "cacheable-request>keyv": "$keyv"
  # Our environment is locked to Node.JS 24+, so there will always be node:sqlite
  "@keyv/sqlite>better-sqlite3": "-"
  "@keyv/sqlite>sqlite3": "-"
