packages:
  - "."
  - "gui/"
  - "modules/*"
catalog:
  "@electron/fuses": ^2.1.2
  keyv: 6.0.0-alpha.3
allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  unrs-resolver: true
patchedDependencies:
  # inlineDynamicImports is deprecated in Vite 8
  "@electron-forge/plugin-vite": patches/@electron-forge__plugin-vite.patch
  # Patches better-sqlite3 out of package.json, so Electron's packaging won't be confused
  "@keyv/sqlite": patches/@keyv__sqlite.patch
  # Fixes compatibility with latest rpmbuild
  electron-installer-redhat@3.4.0: patches/electron-installer-redhat@3.4.0.patch
  # Fixes listener leak
  keyv@6.0.0-alpha.3: patches/keyv@6.0.0-alpha.3.patch
blockExoticSubdeps: false
nodeLinker: hoisted
overrides:
  # Got (cacheable-request) uses Keyv 5, but we are using v6, they are mostly compatible, we are overriding it here, and patch cacheable-request
  "got>keyv": "catalog:"
  "cacheable-request>keyv": "catalog:"
  # Our environment is locked to Node.JS 24+, so there will always be node:sqlite
  "@keyv/sqlite>better-sqlite3": "-"
  "@keyv/sqlite>sqlite3": "-"
  # Safe to upgrade (no actual breaking changes for this project)
  "@electron-forge/plugin-fuses>@electron/fuses": "catalog:"
