/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A connection to the D-Bus session or system bus.
 *
 * Calls are asynchronous and reject with the D-Bus error name and message
 * (for example `"org.freedesktop.DBus.Error.UnknownMethod: …"`).
 */
export declare class DbusClient {
  /** Connect to a bus. `bus` is `"session"` (the default) or `"system"`. */
  constructor(bus?: "session" | "system")
  /** Call a method and resolve with its reply. */
  call(options: DbusCallOptions): Promise<DbusMessage>
  /** Read a property, resolving with the variant it currently holds. */
  getProperty(options: DbusPropertyOptions): Promise<DbusVariant>
  /** Write a property. */
  setProperty(options: DbusSetPropertyOptions): Promise<void>
  /** Read an object's introspection XML. */
  introspect(destination: string, path: string): Promise<string>
  /**
   * Subscribe to signals matching `matches`.
   *
   * The handler is called with `(null, signal)` for every matching signal
   * and may be asynchronous; signals are handed over one at a time, in the
   * order they arrive, and the subscription waits for each handler to
   * settle before the next one. A handler that throws is ignored — a signal
   * has no caller to report the failure to — and does not stop the
   * subscription.
   *
   * Resolves once the bus has registered the match rule, so a subscription
   * never silently misses signals emitted right after it resolves.
   */
  subscribe(matches: DbusSignalMatch, handler: ((err: Error | null, arg: DbusSignal) => Promise<undefined> | undefined)): Promise<DbusSubscription>
  /** Close the connection. Outstanding subscriptions stop receiving signals. */
  disconnect(): Promise<void>
}

/**
 * A live signal subscription.
 *
 * Dropping the handle (or calling [`DbusSubscription::unsubscribe`]) stops
 * the subscription and deregisters its match rule.
 */
export declare class DbusSubscription {
  /** Stop receiving signals. Calling this more than once is a no-op. */
  unsubscribe(): void
  /** Whether this subscription is still listening. */
  get active(): boolean
}

export declare class MediaSession {
  constructor(name: string, identity: string, desktopEntry: string)
  setEventHandler(handler?: (((err: Error | null, arg: MediaSessionEvents) => Promise<undefined> | undefined)) | undefined | null): void
  setMetadata(metadata?: MprisMetadata | undefined | null): Promise<void>
  setVolume(volume: number): Promise<void>
  updatePlaybackState(playbackState?: PlaybackState | undefined | null): Promise<void>
  sendSeeked(time: number): Promise<void>
}

/** Arguments for [`DbusClient::call`]. */
export interface DbusCallOptions {
  /** Well-known or unique name of the service to call. */
  destination: string
  /** Object path of the object that owns the method. */
  path: string
  /** Interface the method belongs to. */
  interfaceName: string
  /** Method name. */
  method: string
  /** D-Bus signature of the arguments, e.g. `"sa{sv}"`. Defaults to none. */
  signature?: string
  /** One element per argument described by `signature`. Defaults to none. */
  body?: unknown[]
}

/** The reply to a method call. */
export interface DbusMessage {
  /** D-Bus signature of the reply body. */
  signature: string
  /** One element per reply argument. */
  body: unknown[]
}

/** Arguments for [`DbusClient::getProperty`]. */
export interface DbusPropertyOptions {
  /** Well-known or unique name of the service to call. */
  destination: string
  /** Object path of the object that owns the property. */
  path: string
  /** Interface that declares the property. */
  interfaceName: string
  /** Property name. */
  name: string
}

/** Arguments for [`DbusClient::setProperty`]. */
export interface DbusSetPropertyOptions {
  /** Well-known or unique name of the service to call. */
  destination: string
  /** Object path of the object that owns the property. */
  path: string
  /** Interface that declares the property. */
  interfaceName: string
  /** Property name. */
  name: string
  /** D-Bus signature of `value`. */
  signature: string
  /** The new value, shaped according to `signature`. */
  value: unknown
}

/** A signal delivered to a subscription handler. */
export interface DbusSignal {
  /** The unique name of the connection that emitted the signal. */
  sender: string
  /** Object path the signal was emitted from. */
  path: string
  /** Interface the signal belongs to. */
  interfaceName: string
  /** Signal name. */
  member: string
  /** D-Bus signature of `body`. */
  signature: string
  /** One element per signal argument. */
  body: unknown[]
}

/**
 * What signals a subscription listens for. Every field is optional; an empty
 * match receives every signal on the bus.
 */
export interface DbusSignalMatch {
  /** Only signals sent by this service. */
  sender?: string
  /** Only signals emitted from this object path. */
  path?: string
  /** Only signals from this interface. */
  interfaceName?: string
  /** Only this signal name. */
  member?: string
}

/** A D-Bus variant: a value together with its own signature. */
export interface DbusVariant {
  /** D-Bus signature of `value`. */
  signature: string
  /** The value, shaped according to `signature`. */
  value: unknown
}

export type MediaSessionEvents =
  | { type: 'Raise' }
  | { type: 'Quit' }
  | { type: 'Play' }
  | { type: 'Pause' }
  | { type: 'Next' }
  | { type: 'Previous' }
  | { type: 'Seek', delta: number }
  | { type: 'SetPosition', position: number }
  | { type: 'SetVolume', volume: number }

export interface MprisMetadata {
  trackId: string
  length?: number
  artUrl?: string
  album?: string
  albumArtist?: Array<string>
  artist?: Array<string>
  lyrics?: string
  title?: string
}

export interface PlaybackState {
  status: PlaybackStatus
  position: number
  speed?: number
}

export declare const enum PlaybackStatus {
  Playing = 0,
  Paused = 1,
  Stopped = 2
}
