/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MediaSession {
  constructor(name: string, identity: string, desktopEntry: string)
  setEventHandler(handler?: (((err: Error | null, arg: MediaSessionEvents) => Promise<undefined> | undefined)) | undefined | null): void
  setMetadata(metadata?: MprisMetadata | undefined | null): object
  setVolume(volume: number): object
  updatePlaybackState(playbackState?: PlaybackState | undefined | null): object
  sendSeeked(time: number): object
}

export type MediaSessionEvents =
  | { type: 'Raise' }
  | { type: 'Quit' }
  | { type: 'Play' }
  | { type: 'Pause' }
  | { type: 'Next' }
  | { type: 'Previous' }
  | { type: 'Seek', delta: number }
  | { type: 'SetPosition', position: number }
  | { type: 'SetVolume', volume: number }

export interface MprisMetadata {
  trackId: string
  length?: number
  artUrl?: string
  album?: string
  albumArtist?: Array<string>
  artist?: Array<string>
  lyrics?: string
  title?: string
}

export interface PlaybackState {
  status: PlaybackStatus
  position: number
  speed?: number
}

export declare const enum PlaybackStatus {
  Playing = 0,
  Paused = 1,
  Stopped = 2
}
