/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Listen for first CursorEnter event of the next created window.
 *
 * Only for Wayland on Linux.
 */
export declare function captureNextWindowFirstCursorEnter(callback: (x: number, y: number) => void): void

export declare const enum DesktopEnvironment {
  Wayland = 0,
  X11 = 1,
  Windows = 2,
  Darwin = 3,
  Unknown = 4
}

export declare function dragWindow(handle: Buffer): void

/**
 * Get current detected desktop environment.
 *
 * Mostly for Linux to use, on Windows/macOS, returns hardcoded values.
 */
export declare function getDesktopEnvironment(): DesktopEnvironment

/**
 * Get the last created window's ID that represents it.
 *
 * Only for Linux.
 */
export declare function getLastCreatedWindowId(): string | null

/**
 * Set regions that the window is used to receive inputs.
 *
 * Only for Linux.
 */
export declare function setInputRegion(windowHandle: string | Buffer, rects?: { x: number, y: number, w: number, h: number }[] | null): boolean
