/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Reserve an xdg_popup role for `target_window_id` on its parent's connection.
 *
 * Only that managed window may consume the reservation. Omit anchor coordinates
 * to use the last pointer-button position on the parent. `shadow_inset` excludes
 * transparent client-side shadow margins from the window geometry.
 * Returns no token when hooks or the required window/anchor/object-ID data
 * are unavailable; callers should retry briefly, then use their overlay path.
 */
export declare function armNextWindowAsPopup(parentWindowId: string, targetWindowId: string, width: number, height: number, anchorX?: number | undefined | null, anchorY?: number | undefined | null, shadowInset?: number | undefined | null): number | null

/**
 * Withdraw the newest pending declaration for `owner`.
 *
 * Omit `owner` to withdraw the newest unnamed declaration.
 */
export declare function cancelLayerShellForNextWindow(owner?: string | undefined | null): boolean

/** Cancel a pending first-cursor-enter capture. */
export declare function cancelNextWindowFirstCursorEnter(token: number): boolean

/** Cancel a popup reservation that has not yet been consumed by its target window. */
export declare function cancelPendingPopup(token: number): boolean

/** Cancel a pending pointer-axis capture. */
export declare function cancelWindowPointerAxisCapture(token: number): boolean

/**
 * Listen for first CursorEnter event of the next created window.
 *
 * Only for Wayland on Linux.
 */
export declare function captureNextWindowFirstCursorEnter(callback: (x: number, y: number) => void): number

/** Invoke once when a Wayland pointer-axis event reaches this window's client. */
export declare function captureWindowNextPointerAxis(windowId: string, callback: (axis: number) => void): number

/**
 * Attach the managed window id to a title, the way the proxy expects it.
 *
 * The window id rides in front of the real title, separated from it by
 * invisible characters, so the proxy can name the window on the wire while the
 * compositor is shown only the title. `ManagedWindow` writes titles through
 * this and nothing else writes them at all.
 */
export declare function decorateWindowTitle(id: string, title: string): string

export declare const enum DesktopEnvironment {
  Wayland = 0,
  X11 = 1,
  Windows = 2,
  Darwin = 3,
  Unknown = 4
}

export declare function dragWindow(hwnd: Buffer): void

/** Release completed native input callbacks on the JavaScript thread. */
export declare function drainWindowCallbacks(): void

/**
 * Gets the position of the cursor
 *
 * Only for X11 on Linux.
 */
export declare function getCursorPosition(): [number, number] | null

/**
 * Get current detected desktop environment.
 *
 * Mostly for Linux to use, on Windows/macOS, returns hardcoded values.
 */
export declare function getDesktopEnvironment(): DesktopEnvironment

/**
 * Whether the compositor advertises `zwlr_layer_shell_v1`.
 *
 * Only meaningful for Wayland on Linux; everywhere else it is `false`.
 */
export declare function isLayerShellAvailable(): boolean

/** Whether this tracked BrowserWindow was actually converted to xdg_popup. */
export declare function isWindowWaylandPopup(windowId: string): boolean

/** The stacking layer a layer surface is placed in, bottom-most first. */
export declare const enum LayerShellLayer {
  Background = 0,
  Bottom = 1,
  Top = 2,
  Overlay = 3
}

/**
 * Layer-shell state for a window the application is about to create.
 *
 * With an owner, applied only to that managed window; without one, applied to
 * the next eligible toplevel. Declare it before the window (or its surface) is
 * brought into existence. A declaration without size or anchors covers the output.
 */
export interface LayerShellOptions {
  /** Purpose of the surface, e.g. `"open-orpheus-menu"`. Required. */
  namespace: string
  /** Defaults to the top layer. */
  layer?: LayerShellLayer
  anchorTop?: boolean
  anchorBottom?: boolean
  anchorLeft?: boolean
  anchorRight?: boolean
  /**
   * Surface size in surface-local coordinates. `0` lets the compositor
   * decide, which requires the two opposite anchors on that axis.
   */
  width?: number
  height?: number
  marginTop?: number
  marginRight?: number
  marginBottom?: number
  marginLeft?: number
  /** `-1` ignore other surfaces, `0` avoid them, `>0` reserve space. */
  exclusiveZone?: number
  /** `0` none, `1` exclusive, `2` on demand (needs layer shell v4). */
  keyboardInteractivity?: number
}

/**
 * Listen for windows whose layer-shell role was refused.
 *
 * A compositor never releases a surface's role, so a window whose surface is
 * already an ordinary toplevel can never become a layer surface. The callback
 * gets the custom window id that was refused; the application has to re-create
 * that window (a new surface) for the role to apply.
 *
 * Only for Wayland on Linux.
 */
export declare function onLayerShellRoleRefused(callback: (windowId: string) => void): void

/**
 * Set regions that the window is used to receive inputs.
 *
 * Only for Linux.
 */
export declare function setInputRegion(windowHandle: string | Buffer, rects?: { x: number, y: number, w: number, h: number }[] | null): boolean

export declare function setWindowAsBackground(hwnd: Buffer): void

/**
 * Whether the active Wayland hooks allow a native popup attempt.
 *
 * Independent of the desktop name. This does not guarantee that a particular
 * window can become a popup: arming still requires a tracked parent, anchor
 * data and a reusable object ID. Callers must retain an overlay fallback.
 */
export declare function supportsNativeWaylandPopup(): boolean

/**
 * Make the next window a layer surface.
 *
 * Must be called before the window — or, for an existing window, its surface —
 * is created: a compositor assigns a surface's role once and never changes it.
 * Returns whether the declaration was accepted; when it is refused the window
 * is still created as an ordinary one.
 * Named declarations belong only to that managed window; omit `owner` to use
 * the next eligible toplevel instead.
 */
export declare function useLayerShellForNextWindow(options: LayerShellOptions, owner?: string | undefined | null): boolean

/**
 * Whether a layer-shell declaration could be sent.
 *
 * The same option validation `useLayerShellForNextWindow` applies, without
 * queueing anything: callers can report a declaration that could never be
 * sent, and a settings UI can check a choice before anything is created.
 *
 * This answers for the options only, never for the compositor: whether it
 * takes layer surfaces at all is `isLayerShellAvailable()`, and a caller that
 * needs both asks both.
 */
export declare function validateLayerShellOptions(options: LayerShellOptions): boolean
