import { execFile as execFileCb } from "node:child_process";
import { resolve } from "node:path";
import { cp, mkdir, readFile, readdir, rm } from "node:fs/promises";
import { promisify } from "node:util";

import { createProjectTarball } from "../common/archive.ts";
import { createPrebuiltBundle } from "../common/prebuilt.ts";
import { CARGO_ZIGBUILD_VERSION, ZIG_VERSION } from "../common/toolchain.ts";
import { cleanOutDir } from "../common/util.ts";
import { createSpecFile } from "./spec.ts";

const execFile = promisify(execFileCb);

export interface BuildSrpmOptions {
  /** Project root. Defaults to the repository root. */
  projectRoot?: string;
  /** Directory that receives the `.src.rpm`; emptied before building. Defaults to `out/make/srpm`. */
  outDir?: string;
  /** Empty `outDir` before building. Defaults to true. */
  clean?: boolean;
  /** Install the build toolchain (rust/node/pnpm) inside `%build`. Defaults to true. */
  installTools?: boolean;
  /** Pass `--nodeps` to rpmbuild to skip the build-dependency check. Defaults to false. */
  nodeps?: boolean;
  /** Path to a prebuilt packaged app dir (out/<name>-linux-<arch>) to bundle as Source1. */
  prebuilt?: string;
}

/**
 * Build the arch-independent source RPM (SRPM) for Copr.
 *
 * Bundles the project source (Source0) and a generated spec, then runs
 * `rpmbuild -bs`. Returns the absolute paths of the produced SRPMs.
 */
export async function buildSrpm(
  options: BuildSrpmOptions = {}
): Promise<string[]> {
  const projectRoot =
    options.projectRoot ?? resolve(import.meta.dirname, "../..");
  const outDir = options.outDir ?? resolve(projectRoot, "out/make/srpm");
  // Empty the directory first so stale artifacts from earlier runs (e.g. an
  // older version) can't be mistaken for this build's output.
  await cleanOutDir(outDir, options.clean);

  const pkg = JSON.parse(
    await readFile(resolve(projectRoot, "package.json"), "utf-8")
  );
  const { rpm: rpmOptions } = await import(
    resolve(projectRoot, "packaging/options.ts")
  );

  const name = rpmOptions.name;
  const version: string = pkg.version;
  const release = "1%{?dist}";

  // --- Step 1: Resolve versions injected into the spec ---
  const nodeVersion = String(
    (pkg.engines?.node ?? "").match(/\d+/)?.[0] ?? "24"
  );
  const cargoToml = await readFile(resolve(projectRoot, "Cargo.toml"), "utf-8");
  const wasmBindgen = cargoToml.match(
    /^\s*wasm-bindgen\s*=\s*["']([^"']+)["']/m
  )?.[1];
  if (!wasmBindgen) {
    throw new Error("Cannot find wasm-bindgen version in Cargo.toml.");
  }
  // `%changelog` entries are generated by the release workflow (DeepSeek) and
  // committed to packaging/resources/rpm.changelog; fall back to a bare header.
  let changelog = `* ${new Date().toString().slice(0, 15)} ${
    pkg.author?.name ?? ""
  } <${pkg.author?.email ?? ""}>
`;
  try {
    changelog = await readFile(
      resolve(projectRoot, "packaging/resources/rpm.changelog"),
      "utf-8"
    );
  } catch {
    // no committed changelog — keep the header-only fallback
  }

  // --- Step 2: Set up the rpmbuild topdir layout ---
  const buildDir = resolve(outDir, "BUILD");
  const rpmsDir = resolve(outDir, "RPMS");
  const sourcesDir = resolve(outDir, "SOURCES");
  const specsDir = resolve(outDir, "SPECS");
  const srpmsDir = resolve(outDir, "SRPMS");
  await Promise.all(
    [buildDir, rpmsDir, sourcesDir, specsDir, srpmsDir].map((dir) =>
      mkdir(dir, { recursive: true })
    )
  );

  const projectTarball = `${name}-${version}.tar.gz`;

  // --- Step 3: Project source tarball (Source0) ---
  await createProjectTarball(
    projectRoot,
    resolve(sourcesDir, projectTarball),
    name,
    version
  );

  // --- Step 3b: Optional prebuilt artifact (Source1) ---
  let prebuiltTarballName: string | undefined;
  if (options.prebuilt) {
    prebuiltTarballName = `${name}-${version}-prebuilt.tar.gz`;
    // Bundle dir named after the tarball's top-level directory so no
    // --transform is needed (prepending a prefix would double-prefix it).
    const bundleDir = resolve(sourcesDir, `${name}-${version}-prebuilt`);
    await createPrebuiltBundle(projectRoot, options.prebuilt, name, bundleDir);
    await execFile("tar", [
      "czf",
      resolve(sourcesDir, prebuiltTarballName),
      "-C",
      sourcesDir,
      `${name}-${version}-prebuilt`,
    ]);
    await rm(bundleDir, { recursive: true, force: true });
  }

  // --- Step 4: Generate the spec ---
  const specPath = resolve(specsDir, `${name}.spec`);
  await createSpecFile(specPath, {
    name,
    version,
    release,
    summary: rpmOptions.description ?? pkg.description,
    description: pkg.description,
    license: rpmOptions.license ?? pkg.license,
    homepage: rpmOptions.homepage ?? pkg.homepage,
    nodeVersion,
    wasmBindgen,
    cargoZigbuild: CARGO_ZIGBUILD_VERSION,
    zig: ZIG_VERSION,
    changelog,
    installTools: options.installTools,
    prebuilt: !!options.prebuilt,
  });

  // --- Step 5: Build the SRPM ---
  const rpmbuildArgs = ["--define", `_topdir ${outDir}`, "-bs"];
  if (options.nodeps) rpmbuildArgs.push("--nodeps");
  rpmbuildArgs.push(specPath);
  await execFile("rpmbuild", rpmbuildArgs);

  // --- Step 6: Collect the SRPM and clean up ---
  const srpms = await readdir(srpmsDir);
  await Promise.all(
    srpms.map((f) => cp(resolve(srpmsDir, f), resolve(outDir, f)))
  );
  await Promise.all(
    [buildDir, rpmsDir, sourcesDir, specsDir, srpmsDir].map((dir) =>
      rm(dir, { recursive: true, force: true })
    )
  );

  return srpms.map((f) => resolve(outDir, f));
}
