name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  changes:
    name: Detect relevant changes
    uses: ./.github/workflows/changes.yml

  build:
    needs: changes
    if: ${{ github.event_name == 'workflow_dispatch' || needs.changes.outputs.build == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - xcode-27
          - windows-latest
          - windows-11-arm

    uses: ./.github/workflows/build.yml
    with:
      runner: ${{ matrix.runner }}
